version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins-controller
    ports:
      - "6922:22"
      - "6980:8080"
    volumes:
       - jenkins_home:/var/jenkins_home
  gitlab:
    image: gitlab/gitlab-ce:17.2.0-ce.0
    container_name: gitlab-server
    ports:
      - "6923:22"
      - "6985:80"
      - "6986:443"
    volumes:
      - gitlab_home:/srv/gitlab
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

volumes:
  jenkins_home:
  gitlab_home: